# Generated by Django 3.1.7 on 2021-04-06 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210401_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likers',
            field=models.ManyToManyField(related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='likers',
            field=models.ManyToManyField(related_name='question_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
